---
# tasks file for netos-plugin-deploy-core

- name: Download plugin from Netos GitLab via Cloudflare Zero Trust
  shell: |
    wget --header="PRIVATE-TOKEN:{{ CUSTOMER_TOKEN }}" \
         --header="{{ CF_ACCESS_CLIENT_ID }}" \
         --header="{{ CF_ACCESS_CLIENT_SECRET }}" \
         -O /netos/working-dir/netos-plugins/{{ PLUGIN_ADD }}-{{ PLUGIN_VERSION }}.tar.gz \
         https://{{ REPO_GIT }}/api/v4/projects/29/repository/files/plugins%2F{{ PLUGIN_ADD }}-{{ PLUGIN_VERSION }}.tar.gz/raw?ref=main
  no_log: true

- name: Get current enabled NetBox plugins from the NetBox configuration.py file
  shell: "grep '^PLUGINS = ' /opt/netbox/netbox/netbox/configuration.py | sed -e 's/^PLUGINS = //' -e 's/[][]//g'"
  register: current_plugins
  failed_when: current_plugins.rc > 1
  no_log: true

- name: Prepare a list of existing plugins from the NetBox configuration.py file
  set_fact:
    existing_plugins: "{{ current_plugins.stdout.split(',') | map('trim') | map('regex_replace', \"'\", '') | select('truthy') }}"
  no_log: true

- name: Add {{ PLUGIN_ADD }} to current plugins list if not already present
  set_fact:
    updated_plugins: "{{ (existing_plugins + [PLUGIN_ADD] | select('truthy')) | unique }}"
  no_log: true

- name: Update PLUGINS entry in configuration.py with values of Netos and existing plugins
  lineinfile:
    path: /opt/netbox/netbox/netbox/configuration.py
    regexp: '^PLUGINS = .*'
    line: "PLUGINS = [{{ updated_plugins | map('regex_replace', '^', \"'\") | map('regex_replace', '$', \"'\") | join(', ') }}]"
    backup: yes

- name: Install the plugin using pip from download in /netos/working-dir/netos-plugins
  pip:
    name: /netos/working-dir/netos-plugins/{{ PLUGIN_ADD }}-{{ PLUGIN_VERSION }}.tar.gz
    virtualenv: /opt/netbox/venv
    virtualenv_site_packages: yes

- name: Run migrations for {{ PLUGIN_ADD }}
  command: "/opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py migrate {{ PLUGIN_ADD }}"

- name: Run collectstatic for NetBox
  command: "/opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input"

- name: Run upgrade for {{ PLUGIN_ADD }} via pip (local execution)
  pip:
    name: "/netos/working-dir/netos-plugins/{{ PLUGIN_ADD }}-{{ PLUGIN_VERSION }}.tar.gz"
    extra_args: "--upgrade --no-cache-dir"
    virtualenv: /opt/netbox/venv
    virtualenv_site_packages: yes
  delegate_to: localhost
  run_once: true
