---
# tasks file for netos-branding-remove

- name: Reverse layout.html logo changes
  replace:
    path: /opt/netbox/netbox/templates/base/layout.html
    regexp: |
      {% raw %}<img src="{% static 'netos_logo.svg' %}" alt="{% trans "Netos logo" %}" width="200px" />{% endraw %}
    replace: |
      {% raw %}<img src="{% static 'netbox_logo.svg' %}" alt="{% trans "NetBox logo" %}" width="200px" />{% endraw %}
  notify:
    - restart netbox services

- name: Reverse login.html logo changes
  replace:
    path: /opt/netbox/netbox/templates/login.html
    regexp: |
      {% raw %}<img src="{% static 'netos_logo.svg' %}" height="80" alt="{% trans "Netos logo" %}" />{% endraw %}
    replace: |
      {% raw %}<img src="{% static 'netbox_logo.svg' %}" height="80" alt="{% trans "NetBox logo" %}" />{% endraw %}
  notify:
    - restart netbox services

- name: Reverse sidenav.html logo changes
  replace:
    path: /opt/netbox/netbox/templates/base/sidenav.html
    regexp: |
      {% raw %}<img src="{% static 'netos_logo.svg' %}" height="48" class="sidenav-brand-img" alt="{% trans "Netos Logo" %}">{% endraw %}
    replace: |
      {% raw %}<img src="{% static 'netbox_logo.svg' %}" height="48" class="sidenav-brand-img" alt="{% trans "NetBox Logo" %}">{% endraw %}
  notify:
    - restart netbox services

- name: Reverse sidenav.html icon changes
  replace:
    path: /opt/netbox/netbox/templates/base/sidenav.html
    regexp: |
      {% raw %}<img src="{% static 'netos_icon.svg' %}" height="32" class="sidenav-brand-img" alt="{% trans "Netos Logo" %}">{% endraw %}
    replace: |
      {% raw %}<img src="{% static 'netbox_icon.svg' %}" height="32" class="sidenav-brand-img" alt="{% trans "NetBox Logo" %}">{% endraw %}
  notify:
    - restart netbox services
