---
# tasks file for nginx

- name: Create certificate directory structure {{ CERT_DIR }} if it doesn't exist
  file:
    path: "{{ CERT_DIR }}"
    state: directory
    mode: '0755'

- name: Ensure nginx is installed
  apt:
    name: nginx
    state: present
  register: apt_result
  retries: 20
  delay: 20
  until: apt_result is succeeded or apt_result is changed

# As there are potentially different services on the server (Semaphore, NetBox, Airflow, Elastic, Kibana, etc.),
# we want to ensure that the endpoints are unique, i.e.
#
# - semaphore.yourdomain.com
# - netbox.youdomain.com
# - airflow.youdomain.com
#
# Ensure that each application has a unique name in the Semaphore Global Settings for each project.

- name: Check for existing server_name in nginx configurations, ignoring netbox.conf
  shell: "grep -l 'server_name {{ NETBOX_HOSTNAME }}.{{ DOMAIN }};' /etc/nginx/sites-enabled/*.conf | grep -v '/etc/nginx/sites-enabled/netbox.conf'"
  register: server_name_conflicts
  ignore_errors: yes

- name: Fail if the {{ NETBOX_HOSTNAME }}.{{ DOMAIN }} already exists in another nginx config file
  fail:
    msg: "Conflict found: server_name '{{ NETBOX_HOSTNAME }}.{{ DOMAIN }}' is already used in {{ server_name_conflicts.stdout_lines }}."
  when: server_name_conflicts.stdout_lines | length > 0

- name: Copy nginx configuration for NetBox
  template: 
    src: "{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
  with_items:
    - netbox
  notify: restart nginx

- name: Create private key (RSA, 4096 bits)
  openssl_privatekey:
    path: "{{ CERT_DIR }}/{{ NETBOX_HOSTNAME }}.{{ DOMAIN }}-private.key"

- name: Create certificate signing request (CSR) for self-signed certificate
  openssl_csr:
    path: /tmp/tmp_csr.csr
    privatekey_path: "{{ CERT_DIR }}/{{ NETBOX_HOSTNAME }}.{{ DOMAIN }}-private.key"
    common_name: "*.{{ DOMAIN }}"
    organization_name: "{{ ORG_NAME }}"
  register: csr

- name: Create self-signed certificate from CSR
  openssl_certificate:
    path: "{{ CERT_DIR }}/{{ NETBOX_HOSTNAME }}.{{ DOMAIN }}.crt"
    csr_path: /tmp/tmp_csr.csr
    privatekey_path: "{{ CERT_DIR }}/{{ NETBOX_HOSTNAME }}.{{ DOMAIN }}-private.key"
    provider: selfsigned
  
- name: Copy nginx.conf global config to /etc/nginx/nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Remove nginx default virtual host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Ensure nginx service is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
