---
# tasks file for netbox-plugin-disable

- name: Get current enabled NetBox plugins from the NetBox configuration.py file
  shell: "grep '^PLUGINS = ' /opt/netbox/netbox/netbox/configuration.py | sed -e 's/^PLUGINS = //' -e 's/[][]//g'"
  register: current_plugins
  failed_when: current_plugins.rc > 1
  no_log: true

- name: Prepare a list of existing plugins in configuration.py
  set_fact:
    existing_plugins: "{{ current_plugins.stdout.split(',') | map('trim') | map('regex_replace', \"'\", '') | select('truthy') }}"
  no_log: true

- name: Remove {{ PLUGIN_ADD }} from the current plugins list if present
  set_fact:
    updated_plugins: "{{ existing_plugins | difference([PLUGIN_ADD]) | select('truthy') }}"
  no_log: true

- name: Update PLUGINS entry in configuration.py by removing {{ PLUGIN_ADD }}
  lineinfile:
    path: /opt/netbox/netbox/netbox/configuration.py
    regexp: '^PLUGINS = .*'
    line: "PLUGINS = [{{ updated_plugins | map('regex_replace', '^', \"'\") | map('regex_replace', '$', \"'\") | join(', ') }}]"
    backup: yes
  notify: 
    - restart netbox services
