---
# handlers file for netos-plugin-deploy-core
- name: restart netbox services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - netbox
    - netbox-rq